# Generated by Django 6.0.7 on 2026-07-11 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('ats_score', 'Resume ATS Score'), ('test_score', 'Test Score'), ('interview_score', 'Interview Score'), ('technical_score', 'Technical Score'), ('communication_score', 'Communication Score'), ('skill_score', 'Skill Score'), ('roadmap_progress', 'Roadmap Progress'), ('overall', 'Overall Progress')], max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('previous_score', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
