# Generated by Django 6.0.7 on 2026-07-11 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(blank=True, default='', max_length=300)),
                ('interview_type', models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('behavioral', 'Behavioral'), ('mixed', 'Mixed')], default='technical', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=50)),
                ('num_questions', models.IntegerField(default=5)),
                ('overall_score', models.IntegerField(default=0)),
                ('technical_score', models.IntegerField(default=0)),
                ('communication_score', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('relevance_score', models.IntegerField(default=0)),
                ('structure_score', models.IntegerField(default=0)),
                ('clarity_score', models.IntegerField(default=0)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('user_answer', models.TextField(blank=True, default='')),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('score', models.IntegerField(default=0)),
                ('technical_score', models.IntegerField(default=0)),
                ('communication_score', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interviews.interviewsession')),
            ],
        ),
    ]
