# Generated by Django 5.2.16 on 2026-09-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_suggestedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='assessed_skill',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
