# Generated by Django 5.2.16 on 2026-09-27 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(help_text='Lowercase, whitespace-normalized name for deduplication', max_length=200, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g., Programming, Soft Skill, Cloud', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['normalized_name'],
            },
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The alias name, usually normalized', max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='skills.skill')),
            ],
            options={
                'verbose_name_plural': 'Skill aliases',
            },
        ),
        migrations.CreateModel(
            name='SkillEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('resume', 'Resume Analysis'), ('assessment', 'Test Assessment'), ('interview', 'AI Interview'), ('roadmap', 'Roadmap Training'), ('project', 'Project Experience'), ('manual', 'Manual Entry')], max_length=50)),
                ('source_reference', models.CharField(blank=True, help_text="e.g., 'resume:5' or 'test:12'", max_length=255, null=True)),
                ('evidence_description', models.TextField(help_text='Context of how this skill was demonstrated')),
                ('score', models.IntegerField(blank=True, help_text='Optional quantitative score (0-100) from this evidence', null=True)),
                ('confidence', models.IntegerField(default=50, help_text='0-100 confidence in this piece of evidence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSkillProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_score', models.IntegerField(default=0, help_text='Overall calculated score (0-100)')),
                ('confidence', models.IntegerField(default=0, help_text='Overall confidence in this score (0-100)')),
                ('evidence_count', models.IntegerField(default=0)),
                ('last_evaluated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_proficiencies', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_proficiencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User skill proficiencies',
                'ordering': ['-proficiency_score'],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
