# Generated by Django 6.0.7 on 2026-07-11 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_career', models.CharField(max_length=300)),
                ('current_skills', models.JSONField(blank=True, default=list)),
                ('experience_level', models.CharField(blank=True, default='beginner', max_length=100)),
                ('study_hours_per_week', models.IntegerField(default=10)),
                ('roadmap_data', models.JSONField(blank=True, default=list)),
                ('progress', models.IntegerField(default=0)),
                ('completed_phases', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('skill_score', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('resume', 'Resume Analysis'), ('test', 'Test Assessment'), ('manual', 'Manual Entry'), ('roadmap', 'Roadmap')], default='manual', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-skill_score'],
                'unique_together': {('user', 'skill_name')},
            },
        ),
    ]
