# Generated by Django 5.2.16 on 2026-09-06 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='learning_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='training_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PhaseTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_index', models.IntegerField()),
                ('phase_name', models.CharField(max_length=300)),
                ('score', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('attempt', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_trainings', to='roadmaps.roadmap')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_trainings', to='assessments.test')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
