# Generated by Django 5.2.16 on 2026-10-01 16:21

import re
from django.db import migrations
from django.db.models import Max

def forwards_func(apps, schema_editor):
    LegacySkill = apps.get_model('roadmaps', 'Skill')
    CanonicalSkill = apps.get_model('skills', 'Skill')
    SkillEvidence = apps.get_model('skills', 'SkillEvidence')
    UserSkillProficiency = apps.get_model('skills', 'UserSkillProficiency')

    for old_skill in LegacySkill.objects.all():
        name = old_skill.skill_name.strip()
        normalized = re.sub(r'\s+', ' ', name.lower())

        # Get or create canonical skill
        c_skill, created = CanonicalSkill.objects.get_or_create(
            normalized_name=normalized,
            defaults={'name': name}
        )

        # Create evidence
        evidence = SkillEvidence.objects.create(
            user_id=old_skill.user_id,
            skill=c_skill,
            source_type='manual',
            source_reference=f"legacy_roadmaps_skill:{old_skill.id}",
            evidence_description="Migrated from legacy roadmaps skill",
            score=old_skill.skill_score,
            confidence=40,
            # Note: We can't set auto_now_add field directly via create without modifying the model field or using specific update, but create is fine.
        )

        # Recalculate proficiency
        evidences = SkillEvidence.objects.filter(user_id=old_skill.user_id, skill=c_skill)
        count = evidences.count()
        max_score = evidences.aggregate(Max('score'))['score__max'] or 0
        confidence = min(90, 40 + (count - 1) * 20) if count > 0 else 0

        proficiency, p_created = UserSkillProficiency.objects.update_or_create(
            user_id=old_skill.user_id,
            skill=c_skill,
            defaults={
                'proficiency_score': max_score,
                'confidence': confidence,
                'evidence_count': count
            }
        )

def reverse_func(apps, schema_editor):
    # Reverse function to recreate legacy skills if rolled back
    SkillEvidence = apps.get_model('skills', 'SkillEvidence')
    LegacySkill = apps.get_model('roadmaps', 'Skill')
    UserSkillProficiency = apps.get_model('skills', 'UserSkillProficiency')

    migrated_evidences = SkillEvidence.objects.filter(source_reference__startswith='legacy_roadmaps_skill:')
    for ev in migrated_evidences:
        skill_name = ev.skill.name
        user_id = ev.user_id
        score = ev.score

        LegacySkill.objects.get_or_create(
            user_id=user_id,
            skill_name=skill_name,
            defaults={'skill_score': score, 'source': 'manual'}
        )
        ev.delete()

        evidences = SkillEvidence.objects.filter(user_id=user_id, skill_id=ev.skill_id)
        count = evidences.count()
        if count == 0:
            UserSkillProficiency.objects.filter(user_id=user_id, skill_id=ev.skill_id).delete()
        else:
            max_score = evidences.aggregate(Max('score'))['score__max'] or 0
            confidence = min(90, 40 + (count - 1) * 20)
            UserSkillProficiency.objects.filter(user_id=user_id, skill_id=ev.skill_id).update(
                proficiency_score=max_score,
                confidence=confidence,
                evidence_count=count
            )

class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_roadmap_learning_progress_roadmap_training_scores_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
