# Generated by Django 6.0.7 on 2026-07-11 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('ats_score', models.IntegerField(default=0)),
                ('previous_ats_score', models.IntegerField(default=0)),
                ('target_role', models.CharField(blank=True, default='', max_length=300)),
                ('job_description', models.TextField(blank=True, default='')),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
