# Generated by Django 5.2.16 on 2026-09-27 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCareerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_title', models.CharField(blank=True, max_length=200, null=True)),
                ('target_company', models.CharField(blank=True, max_length=200, null=True)),
                ('target_industry', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_targeting', to='careers.careerrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerRoleSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('critical', 'Critical (Must Have)'), ('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low / Nice to Have')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='careers.careerrole')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='skills.skill')),
            ],
            options={
                'ordering': ['role', 'skill'],
                'unique_together': {('role', 'skill')},
            },
        ),
    ]
