# Generated by Django 5.2.16 on 2026-09-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerroleskillrequirement',
            name='required_proficiency',
            field=models.IntegerField(blank=True, help_text='Required proficiency score (0-100)', null=True),
        ),
    ]
