# Generated by Django 5.2.16 on 2026-09-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='academic_year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('graduated', 'Graduated'), ('job_seeker', 'Job Seeker')], default='1', max_length=20),
        ),
    ]
