# Generated by Django 5.2.16 on 2026-09-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='SYSTEM', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
